#!/usr/bin/env bash
# export.sh — copies THIS Mac's LIVE config INTO the repo (to "seed" it).
# Run this ONCE on your best-configured machine, then commit + push.
# On other machines use install.sh (which creates symlinks; no export needed there).
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
USER_DIR="$HOME/Library/Application Support/Cursor/User"

CURSOR_BIN=""
if command -v cursor >/dev/null 2>&1; then
  CURSOR_BIN="cursor"
elif [ -x "/Applications/Cursor.app/Contents/Resources/app/bin/cursor" ]; then
  CURSOR_BIN="/Applications/Cursor.app/Contents/Resources/app/bin/cursor"
fi

copy() {
  local src="$1" dst="$2"
  if [ -L "$src" ]; then
    echo "    skip (already a symlink to the repo): $(basename "$src")"
    return
  fi
  if [ -e "$src" ]; then
    cp -R "$src" "$dst"
    echo "    copied: $(basename "$src")"
  else
    echo "    not present on this machine: $(basename "$src")"
  fi
}

echo "==> Exporting this Mac's config into the repo"
copy "$USER_DIR/settings.json"    "$REPO_DIR/settings.json"
copy "$USER_DIR/keybindings.json" "$REPO_DIR/keybindings.json"
if [ -d "$USER_DIR/snippets" ] && [ ! -L "$USER_DIR/snippets" ]; then
  rm -rf "$REPO_DIR/snippets"
  cp -R "$USER_DIR/snippets" "$REPO_DIR/snippets"
  echo "    copied: snippets/"
fi

echo "==> Regenerating extensions.txt"
if [ -n "$CURSOR_BIN" ]; then
  {
    echo "# Cursor extensions — regenerated by export.sh ($(date +%Y-%m-%d))"
    "$CURSOR_BIN" --list-extensions
  } > "$REPO_DIR/extensions.txt"
  echo "    ok ($("$CURSOR_BIN" --list-extensions | wc -l | tr -d ' ') extensions)"
else
  echo "    (!) 'cursor' CLI not found; extensions.txt unchanged."
fi

echo "==> Done. Now: git add -A && git commit -m 'seed cursor config' && git push"
